# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleImageKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleImageKit

  target 'SimpleImageKitTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    # Pods for testing
  end

  target 'SimpleImageKitUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
